<div class="jumbotron">
    <h1> PHPUnit Workshop</h1>
    <p>este es el workshop de php unit de la conferencia <a href="http://tech.meetup.uy/">Tech Meetup UY 2013</a></p>
</div>

<div class="row">

    <div class="col-md-4">

            <?php echo $this->first?>

    </div>

    <div class="col-md-4">

        <?php echo $this->second?>

    </div>

    <div class="col-md-4">
        <?php echo $this->third?>
    </div>
</div>
